# Generated by Django 5.1.4 on 2025-08-15 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vestibular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Vestibular',
                'verbose_name_plural': 'Vestibulares',
                'unique_together': {('nome', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('resposta_geral', models.IntegerField(null=True)),
                ('eh_idioma', models.BooleanField(default=False)),
                ('vestibular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='api.vestibular')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'unique_together': {('vestibular', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='GabaritoIdioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=20)),
                ('resposta_idioma', models.IntegerField(null=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gabaritos_idioma', to='api.questao')),
            ],
            options={
                'verbose_name': 'Gabarito de Idioma',
                'verbose_name_plural': 'Gabaritos de Idiomas',
                'unique_together': {('questao', 'idioma')},
            },
        ),
    ]
