# Generated by Django 5.1.4 on 2025-08-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestibular',
            name='tipo',
            field=models.CharField(choices=[('VESTIBULAR', 'vestibular'), ('PAS', 'pas')], default='VESTIBULAR'),
        ),
    ]
