# Generated by Django 5.1.4 on 2025-08-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
    ]
