# Generated by Django 5.1.4 on 2025-08-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vestibular_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestibular',
            name='tipo',
            field=models.CharField(choices=[('vestibular', 'VESTIBULAR'), ('pas', 'PAS')], default='VESTIBULAR'),
        ),
    ]
