# Generated by Django 5.1.4 on 2025-08-18 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_questao_anulada"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questao",
            name="anulada",
        ),
    ]
