# Generated by Django 5.1.4 on 2025-10-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_questao_anulada'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestibular',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='questao',
            name='resposta_geral',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
