# Generated by Django 5.1.4 on 2025-08-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_questao_anulada"),
    ]

    operations = [
        migrations.AddField(
            model_name="questao",
            name="anulada",
            field=models.BooleanField(default=False),
        ),
    ]
