# Generated by Django 5.1.4 on 2025-08-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_vestibular_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestibular',
            name='serie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
