# Generated by Django 5.1.4 on 2025-08-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vestibular_serie'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vestibular',
            unique_together={('nome', 'ano', 'serie')},
        ),
    ]
