# Generated by Django 5.1.4 on 2025-08-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_questao_anulada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questao",
            name="resposta_geral",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
