# Generated by Django 5.1.4 on 2025-10-29 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_vestibular_ativo_alter_questao_resposta_geral"),
        ("api", "0005_alter_questao_resposta_geral"),
    ]

    operations = []
