# Generated by Django 5.1.4 on 2026-03-20 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_vestibulares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('anulada', models.BooleanField(default=False)),
                ('resposta_geral', models.IntegerField(blank=True, null=True)),
                ('vestibular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='a_vestibulares.vestibular')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'unique_together': {('vestibular', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='GabaritoIdioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(choices=[('ingles', 'Inglês'), ('espanhol', 'Espanhol')], max_length=20)),
                ('resposta', models.IntegerField()),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gabaritos_idioma', to='a_questoes.questao')),
            ],
            options={
                'verbose_name': 'Gabarito de Idioma',
                'verbose_name_plural': 'Gabaritos de Idiomas',
                'unique_together': {('questao', 'idioma')},
            },
        ),
    ]
