# Generated by Django 5.1.4 on 2026-03-20 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_questoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gabaritoidioma',
            name='resposta',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='questao',
            name='numero',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='questao',
            name='resposta_geral',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
