# Generated by Django 5.1.4 on 2026-03-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_questoes', '0002_alter_gabaritoidioma_resposta_alter_questao_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gabaritoidioma',
            name='idioma',
            field=models.CharField(choices=[('ingles', 'Inglês'), ('espanhol', 'Espanhol'), ('frances', 'Francês')], max_length=20),
        ),
    ]
