# Generated by Django 5.1.4 on 2026-03-20 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_questoes', '0003_alter_gabaritoidioma_idioma'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GabaritoIdioma',
            new_name='QuestaoIdioma',
        ),
    ]
