# Generated by Django 6.0.3 on 2026-03-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_questoes', '0004_rename_gabaritoidioma_questaoidioma'),
    ]

    operations = [
        migrations.AddField(
            model_name='questaoidioma',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
    ]
