# Generated by Django 5.1.4 on 2026-03-20 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vestibular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2030)])),
                ('tipo', models.CharField(choices=[('vestibular', 'VESTIBULAR'), ('pas', 'PAS')], default='VESTIBULAR', max_length=50)),
                ('serie', models.IntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vestibular',
                'verbose_name_plural': 'Vestibulares',
                'unique_together': {('nome', 'ano', 'serie')},
            },
        ),
    ]
