# Generated by Django 5.1.4 on 2026-03-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_vestibulares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestibular',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='vestibulares/'),
        ),
    ]
