# Generated by Django 5.1.4 on 2026-03-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_vestibulares', '0002_vestibular_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='vestibular',
            name='com_gabarito',
            field=models.BooleanField(default=False),
        ),
    ]
