# Generated by Django 5.1.4 on 2026-03-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_vestibulares', '0003_vestibular_com_gabarito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vestibular',
            name='ativo',
        ),
    ]
